import {RouterModule, Routes} from '@angular/router';
import {EmployeesComponent} from './staff/employees/employees/employees.component';
import {EmployeeComponent} from './staff/employees/employee/employee.component';
import {AddEmployeeComponent} from './staff/employees/add-employee/add-employee.component';
import {TeamsComponent} from './staff/teams/teams/teams.component';
import {TeamComponent} from './staff/teams/team/team.component';
import {AddHolidayComponent} from './staff/holidays/add-holiday/add-holiday.component';
import {TasksComponent} from './production/tasks/tasks/tasks.component';
import {TaskComponent} from './production/tasks/task/task.component';
import {AddTaskComponent} from './production/tasks/add-task/add-task.component';
import {ReportsComponent} from './production/finance/reports/reports.component';
import {ReportComponent} from './production/finance/report/report.component';
import {CurrentReportComponent} from './production/finance/current-report/current-report.component';
import {DeliveriesComponent} from './shop/deliveries/deliveries/deliveries.component';
import {DeliveryComponent} from './shop/deliveries/delivery/delivery.component';
import {AddDeliveryComponent} from './shop/deliveries/add-delivery/add-delivery.component';
import {ItemsComponent} from './shop/items/items/items.component';
import {ItemComponent} from './shop/items/item/item.component';
import {AddItemComponent} from './shop/items/add-item/add-item.component';
import {LoginComponent} from './security/login/login.component';
import {ValidateComponent} from './security/validate/validate.component';
import {SpecialPlansComponent} from './production/planning/special-plans/special-plans.component';
import {PlanningComponent} from './production/planning/planning/planning.component';
import {UpdateDailyPlanComponent} from './production/planning/update-daily-plan/update-daily-plan.component';
import {AddOrderComponent} from './shop/orders/add-order/add-order.component';
import {AddNotificationComponent} from './communication/notifications/add-notification/add-notification.component';
import {AddSuggestionComponent} from './communication/suggestions/add-suggestion/add-suggestion.component';
import {OrderComponent} from './shop/orders/order/order.component';
import {OrdersComponent} from './shop/orders/orders/orders.component';
import {NotificationComponent} from './communication/notifications/notification/notification.component';
import {NotificationsComponent} from './communication/notifications/notifications/notifications.component';
import {SuggestionComponent} from './communication/suggestions/suggestion/suggestion.component';
import {SuggestionsComponent} from './communication/suggestions/suggestions/suggestions.component';
import {ReturnsComponent} from './shop/returns/returns/returns.component';
import {ReturnComponent} from './shop/returns/return/return.component';
import {ComplaintsComponent} from './shop/complaints/complaints/complaints.component';
import {ComplaintComponent} from './shop/complaints/complaint/complaint.component';
import {InboxComponent} from './communication/emails/inbox/inbox.component';
import {OutboxComponent} from './communication/emails/outbox/outbox.component';
import {ConversationComponent} from './communication/emails/conversation/conversation.component';
import {AddEmailComponent} from './communication/emails/add-email/add-email.component';
import {KanbanComponent} from './production/tasks/kanban/kanban.component';
import {SetupComponent} from "./setup/setup.component";

export const appRoutes: Routes = [
  {path: 'employees', component: EmployeesComponent},
  {path: 'employees/add', component: AddEmployeeComponent},
  {path: 'employees/:id', component: EmployeeComponent},
  {path: 'employees/:id/validate', component: ValidateComponent},
  {path: 'teams', component: TeamsComponent},
  {path: 'teams/:id', component: TeamComponent},
  {path: 'holidays/add', component: AddHolidayComponent},
  {path: 'tasks', component: TasksComponent},
  {path: 'tasks/add', component: AddTaskComponent},
  {path: 'tasks/:id', component: TaskComponent},
  {path: 'tasks/:id/assign', component: TaskComponent},
  {path: 'reports', component: ReportsComponent},
  {path: 'reports/:id', component: ReportComponent},
  {path: 'current-report', component: CurrentReportComponent},
  {path: 'deliveries', component: DeliveriesComponent},
  {path: 'deliveries/add', component: AddDeliveryComponent},
  {path: 'deliveries/:id', component: DeliveryComponent},
  {path: 'items', component: ItemsComponent},
  {path: 'items/add', component: AddItemComponent},
  {path: 'items/:id', component: ItemComponent},
  {path: 'planning', component: PlanningComponent},
  {path: 'planning/update', component: UpdateDailyPlanComponent},
  {path: 'special-plans', component: SpecialPlansComponent},
  {path: 'login', component: LoginComponent},
  {path: 'notifications', component: NotificationsComponent},
  {path: 'notifications/add', component: AddNotificationComponent},
  {path: 'notifications/:id', component: NotificationComponent},
  {path: 'orders', component: OrdersComponent},
  {path: 'shop-service/add', component: AddOrderComponent},
  {path: 'orders/:id', component: OrderComponent},
  {path: 'suggestions', component: SuggestionsComponent},
  {path: 'suggestions/add', component: AddSuggestionComponent},
  {path: 'suggestions/:id', component: SuggestionComponent},
  {path: 'returns', component: ReturnsComponent},
  {path: 'returns/:id', component: ReturnComponent},
  {path: 'complaints', component: ComplaintsComponent},
  {path: 'complaints/:id', component: ComplaintComponent},
  {path: 'emails/inbox', component: InboxComponent},
  {path: 'emails/outbox', component: OutboxComponent},
  {path: 'emails/add', component: AddEmailComponent},
  {path: 'emails/:id', component: ConversationComponent},
  {path: 'login', component: LoginComponent},
  {path: 'setup', component: SetupComponent},
  {path: 'kanban/:id', component: KanbanComponent}
  // {path: '**', redirectTo: 'login'}
  ];

export const routing = RouterModule.forRoot(appRoutes);
